export const themes = {
  pastel: {
    name: "pastel",
    background: "#FDF2F8",
    card: "#FCE7F3",
    textPrimary: "#9D174D",
    textTitle: "#BE185D",
    buttonStart: "#EC4899",
    buttonPause: "#F9A8D4",
    buttonReset: "#F43F5E",
    accent: "#C084FC",
    tabBar: "#FBCFE8",
  },

  dark: {
    name: "dark",
    background: "#020617",
    card: "#0f172a",
    textPrimary: "#e2e8f0",
    textTitle: "#f8fafb",
    buttonStart: "#22c55e",
    buttonPause: "#facc15",
    buttonReset: "#ef4444",
    accent: "#38bdf8",
    tabBar: "#0f172a",
  },

  neon: {
    name: "neon",
    background: "#0F0A19",
    card: "#1A1033",
    textPrimary: "#EDE9FE",
    textTitle: "#C084FC",
    buttonStart: "#8B5CF6",
    buttonPause: "#A78BFA",
    buttonReset: "#F87171",
    accent: "#38BDF8",
    tabBar: "#1A1033",
  },

  minimal: {
    name: "minimal",
    background: "#F8FAFC",
    card: "#ffffff",
    textPrimary: "#1E293B",
    textTitle: "#0F172A",
    buttonStart: "#3B82F6",
    buttonPause: "#FACC15",
    buttonReset: "#EF4444",
    accent: "#6366F1",
    tabBar: "#e2e8f0",
  },

  sunshine: {
    name: "sunshine",
    background: "#FFF7ED",
    card: "#FFE7C2",
    textPrimary: "#7C2D12",
    textTitle: "#9A3412",
    buttonStart: "#F97316",
    buttonPause: "#FDBA74",
    buttonReset: "#EA580C",
    accent: "#FFB703",
    tabBar: "#FFD39A",
  },
};
